apiVersion: apps/v1 
kind: Deployment
metadata:
  name: alpinedeployment
  namespace: k8s-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpineapp
  strategy: 
    type: Recreate
  template:
    metadata:
      name: alpinepod
      labels:
        app: alpineapp
    spec:
      containers:
        - name: alpinecontainer
          image: nginx:latest 
          ports:
            - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: alpinesvc
  namespace: k8s-ns
spec:
  type: NodePort
  selector:
    app: alpineapp
  ports:
   -  port: 80
      targetPort: 8090
