apiVersion: apps/v1 
kind: Deployment
metadata:
  name: javawebappdeployment
  namespace: k8s-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  strategy:
    type: Recreate
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapp
    spec:
      containers:
        - name: javawebappcontainer
          image: dockerhandson/java-web-app:1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: k8s-ns
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
   -  port: 80
      targetPort: 8080
