apiVersion: v1
kind: Pod
metadata:
   name: nodejspod
   labels: 
     app: nodeapp
   namespace: k8s-ns
spec:
  containers:
    - name: nodeappcontainer
      image: dockerhandson/node-app-mss:1
      ports:
       - containerPort: 9981
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsappsvc
  namespace: k8s-ns
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
   -  port: 80
      targetPort: 9981
