apiVersion: v1
kind: ReplicationController
metadata:
  name: javawebapprc
  namespace: k8s-ns
spec:
  replicas: 1
  selector:
    app: javawebapp
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapp
    spec:
      containers:
        - name: javawebappcontainer
          image: dockerhandson/java-web-app
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: k8s-ns
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
   -  port: 80
      targetPort: 8080
