apiVersion: apps/v1 
kind: ReplicaSet
metadata:
  name: javawebapprs
  namespace: k8s-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javawebapprs
  template:
    metadata:
      name: javawebapppodrs
      labels:
        app: javawebapprs
    spec:
      containers:
        - name: javawebappcontainer
          image: dockerhandson/java-web-app:1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvcrs
  namespace: k8s-ns
spec:
  type: NodePort
  selector:
    app: javawebapprs
  ports:
   -  port: 80
      targetPort: 8080
